TemplateProject/TemplateProject/TemplateApp/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'template_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('home/<first_name>/<last_name>', views.home, name='home'),
    path('sample1', views.sample1, name='sample1'),
    path('sample2', views.sample2, name='sample2'),
    path('sample', views.sample, name='sample'),
    path('sample3', views.sample3, name='sample3')
]

TemplateProject/TemplateProject/TemplateProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('template_app/', include('TemplateApp.urls')),
]

TemplateProject/TemplateProject/TemplateApp/models.py
from django.db import models

# Create your models here.

TemplateProject/TemplateProject/TemplateApp/views.py
from django.http import request
from django.shortcuts import render

# Create your views here.
def index(request):
    val = 'my_context'
    return render(request, 'index.html', context={'value': val})


def home(request, first_name, last_name):
    my_name = f"{first_name} {last_name}"
    favorite_fruits = ['Apple', 'Grape', 'Lemon']
    my_info = {
        'name' : 'Taro',
        'age': '17'
    }
    status = 20
    return render(request, 'home.html', context={
        'my_name': my_name,
        'favorite_fruits': favorite_fruits,
        'my_info': my_info,
        'status': status
    })

def sample1(request):
    return render(request, 'sample1.html')

def sample2(request):
    return render(request, 'sample2.html')

def sample(request):
    name = 'Taro  Yamada'
    height = 175.5
    weight = 72
    bmi = weight / (height / 100) ** 2
    page_url = 'ホームページ: https://www.google.com'
    favorite_fruits = ['Apple', 'Grape', 'Lemon']
    msg="""
    hello
    my name is 
    ichiro
    """
    msg2="123456789"
    return render(request, 'sample.html',context={
        'name': name,
        'height':height,
        'bmi': bmi,
        'page_url':page_url,
        'fruits':favorite_fruits,
        'msg':msg,
        'msg2':msg2
    })


class Country:
    def __init__(self, name, population, capital):
        self.name=name
        self.population=population
        self.capital=capital

    
def sample3(request):
    country = Country('Japan', 100000000, 'Tokyo')
    return render(request, 'sample3.html', context={
        'country': country
    })

TemplateProject/TemplateProject/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset  = 'utf-8'>
        <title>{% block title %}My Page{% endblock%}</title>
    </head>
    <body>
        <h1>My page</h1>
        {% block content %}{% endblock %}
    </body>
</html>

TemplateProject/TemplateProject/templates/home.html
{% load event_tags %}

{% comment %} <h1>Name: {{ my_name }}</h1>
<h2>fruits: {{ favorite_fruits.2 }}</h2>
<h3>Age: {{ my_info.age }} </h3> {% endcomment %}
{{ my_name }}
{# for #}
<ul>
    {% for fruit in favorite_fruits %}
        <li>{{ fruit }}</li>
    {% endfor %}
</ul>
{% if 'grape' in favorite_fruits %}
    <p> {{ favorite_fruits.1 }} あります </p>
{% elif 'gemon' in favorite_fruits %}
    <p> {{ favorite_fruits.2 }} あります </p>
{% else %}
    <p> Not Found</p>
{% endif %}

{% if 'age' in my_info %}
<p> age is {{my_info.age}} </p>
    {% if my_info.age < 20 %}
        <p>未成年</p>
    {% endif %}
{% endif %}

<p>{{ status | status_to_string }} </p>

TemplateProject/TemplateProject/templates/index.html
<h1>tempapp</h1>
<p>{{ value }} </p>

TemplateProject/TemplateProject/templates/sample.html
{% load static %}
<link rel='stylesheet' type='text/css' href="{% static 'download/home.css' %}"
<h1>{{name | upper}}</h1>
<h1>{{page_url | urlize}}</h1>
<h1>BMI: {{bmi | floatformat:2}}</h1>
<h1>salary: {{salary | default:'秘密'}}</h1>
<p>{{fruits | join:', '| upper}}</p>
<p>{{fruits | random}}</p>
<p>{{msg | linebreaks}}</p>
<p>{{msg2 | truncatechars:5}}</p>
<a href="{% url 'template_app:home' first_name='Saburo' last_name='Suzuki' %}">home</a>
<br></br>
<img src="{% static 'download/sample.jpg' %}">

TemplateProject/TemplateProject/templates/sample1.html
{% extends 'base.html' %}
{% block title %} Sample1{{ block.super }}{% endblock%}
{% block content %}
<p>Sample1</p>
{% endblock%}

TemplateProject/TemplateProject/templates/sample2.html
{% extends 'base.html' %}
{% block title %}Sample2{{ block.super }}{% endblock%}
{% block content %}
<p>Sample2</p>
{% endblock%}

TemplateProject/TemplateProject/templates/sample3.html
国名： {{country.name}}<br>
人口： {{country.population}}<br>
首都： {{country.capital}}